version: "3.9"
services:
  gateway-service:
    environment:
      JWT_KEY: ${JWT_KEY-DEVELOP_KEY}
      ADMIN_ID: ${ADMIN_ID-DEVELOP_ID}
      ADMIN_SECRET: ${ADMIN_SECRET-DEVELOP_SECRET}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./build/gateway.Dockerfile
    ports:
      - "${GATEWAY_SERVICE_PORT-3000}:3000"
    extra_hosts:
      - "localhost:192.168.31.112"
  reservation-service:
    environment:
      JWT_KEY: ${JWT_KEY-DEVELOP_KEY}
      ADMIN_ID: ${ADMIN_ID-DEVELOP_ID}
      ADMIN_SECRET: ${ADMIN_SECRET-DEVELOP_SECRET}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./build/reservation.Dockerfile
    ports:
      - "${RESERVATION_SERVICE_PORT-3001}:3000"
    extra_hosts:
      - "localhost:192.168.31.112"
    depends_on:
      - db
  auth-service:
    environment:
      JWT_KEY: ${JWT_KEY-DEVELOP_KEY}
      ADMIN_ID: ${ADMIN_ID-DEVELOP_ID}
      ADMIN_SECRET: ${ADMIN_SECRET-DEVELOP_SECRET}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./build/auth.Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT-3002}:3000"
    extra_hosts:
      - "localhost:192.168.31.112"
    depends_on:
      - db
  hotel-service:
    environment:
      JWT_KEY: ${JWT_KEY-DEVELOP_KEY}
      ADMIN_ID: ${ADMIN_ID-DEVELOP_ID}
      ADMIN_SECRET: ${ADMIN_SECRET-DEVELOP_SECRET}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./build/hotel.Dockerfile
    ports:
      - "${HOTEL_SERVICE_PORT-3003}:3000"
    extra_hosts:
      - "localhost:192.168.31.112"
    depends_on:
      - db
  loyalty-service:
    environment:
      JWT_KEY: ${JWT_KEY-DEVELOP_KEY}
      ADMIN_ID: ${ADMIN_ID-DEVELOP_ID}
      ADMIN_SECRET: ${ADMIN_SECRET-DEVELOP_SECRET}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./build/loyalty.Dockerfile
    ports:
      - "${LOYALTY_SERVICE_PORT-3004}:3000"
    extra_hosts:
      - "localhost:192.168.31.112"
    depends_on:
      - db
  payment-service:
    environment:
      JWT_KEY: ${JWT_KEY-DEVELOP_KEY}
      ADMIN_ID: ${ADMIN_ID-DEVELOP_ID}
      ADMIN_SECRET: ${ADMIN_SECRET-DEVELOP_SECRET}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./build/payment.Dockerfile
    ports:
      - "${PAYMENT_SERVICE_PORT-3005}:3000"
    extra_hosts:
      - "localhost:192.168.31.112"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_MULTIPLE_DATABASES=authdb,hoteldb,loyaltydb,paymentdb,reservationdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
