// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/pkg/delivery/grpc/payment-service/proto/scheme.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	commonProto "hotel-booking-system/internal/pkg/delivery/grpc/commonProto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Price struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Price) Reset() {
	*x = Price{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescGZIP(), []int{0}
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid *commonProto.UUID `protobuf:"bytes,1,opt,name=UserUuid,proto3" json:"UserUuid,omitempty"`
	Value    int64             `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetUserUuid() *commonProto.UUID {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *CreatePaymentRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Payment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentUuid *commonProto.UUID `protobuf:"bytes,1,opt,name=PaymentUuid,proto3" json:"PaymentUuid,omitempty"`
	UserUuid    *commonProto.UUID `protobuf:"bytes,2,opt,name=UserUuid,proto3" json:"UserUuid,omitempty"`
	Status      string            `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Price       int64             `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	TimeUpdated int64             `protobuf:"varint,5,opt,name=TimeUpdated,proto3" json:"TimeUpdated,omitempty"`
}

func (x *Payment) Reset() {
	*x = Payment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescGZIP(), []int{2}
}

func (x *Payment) GetPaymentUuid() *commonProto.UUID {
	if x != nil {
		return x.PaymentUuid
	}
	return nil
}

func (x *Payment) GetUserUuid() *commonProto.UUID {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Payment) GetTimeUpdated() int64 {
	if x != nil {
		return x.TimeUpdated
	}
	return 0
}

var File_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto protoreflect.FileDescriptor

var file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x33, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x22, 0x56, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb3, 0x01, 0x0a,
	0x07, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x0b, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x32, 0xae, 0x01, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55,
	0x55, 0x49, 0x44, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x55, 0x49,
	0x44, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x00, 0x42, 0x47, 0x5a, 0x45, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2d, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescOnce sync.Once
	file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescData = file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDesc
)

func file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescGZIP() []byte {
	file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescOnce.Do(func() {
		file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescData)
	})
	return file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDescData
}

var file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_goTypes = []interface{}{
	(*Price)(nil),                   // 0: proto.Price
	(*CreatePaymentRequest)(nil),    // 1: proto.CreatePaymentRequest
	(*Payment)(nil),                 // 2: proto.Payment
	(*commonProto.UUID)(nil),        // 3: common.UUID
	(*commonProto.Credentials)(nil), // 4: common.Credentials
	(*commonProto.Token)(nil),       // 5: common.Token
}
var file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_depIdxs = []int32{
	3, // 0: proto.CreatePaymentRequest.UserUuid:type_name -> common.UUID
	3, // 1: proto.Payment.PaymentUuid:type_name -> common.UUID
	3, // 2: proto.Payment.UserUuid:type_name -> common.UUID
	4, // 3: proto.PaymentService.GetToken:input_type -> common.Credentials
	1, // 4: proto.PaymentService.CreatePayment:input_type -> proto.CreatePaymentRequest
	3, // 5: proto.PaymentService.GetPayment:input_type -> common.UUID
	5, // 6: proto.PaymentService.GetToken:output_type -> common.Token
	3, // 7: proto.PaymentService.CreatePayment:output_type -> common.UUID
	2, // 8: proto.PaymentService.GetPayment:output_type -> proto.Payment
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_init() }
func file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_init() {
	if File_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Price); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePaymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_goTypes,
		DependencyIndexes: file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_depIdxs,
		MessageInfos:      file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_msgTypes,
	}.Build()
	File_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto = out.File
	file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_rawDesc = nil
	file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_goTypes = nil
	file_internal_pkg_delivery_grpc_payment_service_proto_scheme_proto_depIdxs = nil
}
