// source: internal/pkg/delivery/grpc/loyalty-service/proto/scheme.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var internal_pkg_delivery_grpc_commonProto_common_pb = require('../../../../../../internal/pkg/delivery/grpc/commonProto/common_pb.js');
goog.object.extend(proto, internal_pkg_delivery_grpc_commonProto_common_pb);
goog.exportSymbol('proto.proto.Loyalty', null, global);
goog.exportSymbol('proto.proto.UpdateDiscountRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.UpdateDiscountRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.UpdateDiscountRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.UpdateDiscountRequest.displayName = 'proto.proto.UpdateDiscountRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.Loyalty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.Loyalty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.Loyalty.displayName = 'proto.proto.Loyalty';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.UpdateDiscountRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.UpdateDiscountRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.UpdateDiscountRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.UpdateDiscountRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    useruid: (f = msg.getUseruid()) && internal_pkg_delivery_grpc_commonProto_common_pb.UUID.toObject(includeInstance, f),
    contribution: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.UpdateDiscountRequest}
 */
proto.proto.UpdateDiscountRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.UpdateDiscountRequest;
  return proto.proto.UpdateDiscountRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.UpdateDiscountRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.UpdateDiscountRequest}
 */
proto.proto.UpdateDiscountRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new internal_pkg_delivery_grpc_commonProto_common_pb.UUID;
      reader.readMessage(value,internal_pkg_delivery_grpc_commonProto_common_pb.UUID.deserializeBinaryFromReader);
      msg.setUseruid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setContribution(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.UpdateDiscountRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.UpdateDiscountRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.UpdateDiscountRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.UpdateDiscountRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUseruid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      internal_pkg_delivery_grpc_commonProto_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getContribution();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional common.UUID userUid = 1;
 * @return {?proto.common.UUID}
 */
proto.proto.UpdateDiscountRequest.prototype.getUseruid = function() {
  return /** @type{?proto.common.UUID} */ (
    jspb.Message.getWrapperField(this, internal_pkg_delivery_grpc_commonProto_common_pb.UUID, 1));
};


/**
 * @param {?proto.common.UUID|undefined} value
 * @return {!proto.proto.UpdateDiscountRequest} returns this
*/
proto.proto.UpdateDiscountRequest.prototype.setUseruid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.UpdateDiscountRequest} returns this
 */
proto.proto.UpdateDiscountRequest.prototype.clearUseruid = function() {
  return this.setUseruid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.UpdateDiscountRequest.prototype.hasUseruid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional float contribution = 2;
 * @return {number}
 */
proto.proto.UpdateDiscountRequest.prototype.getContribution = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.proto.UpdateDiscountRequest} returns this
 */
proto.proto.UpdateDiscountRequest.prototype.setContribution = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.Loyalty.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.Loyalty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.Loyalty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Loyalty.toObject = function(includeInstance, msg) {
  var f, obj = {
    useruuid: (f = msg.getUseruuid()) && internal_pkg_delivery_grpc_commonProto_common_pb.UUID.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 2, ""),
    discount: jspb.Message.getFieldWithDefault(msg, 3, 0),
    contributionamount: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.Loyalty}
 */
proto.proto.Loyalty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.Loyalty;
  return proto.proto.Loyalty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.Loyalty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.Loyalty}
 */
proto.proto.Loyalty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new internal_pkg_delivery_grpc_commonProto_common_pb.UUID;
      reader.readMessage(value,internal_pkg_delivery_grpc_commonProto_common_pb.UUID.deserializeBinaryFromReader);
      msg.setUseruuid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDiscount(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setContributionamount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.Loyalty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.Loyalty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.Loyalty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Loyalty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUseruuid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      internal_pkg_delivery_grpc_commonProto_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDiscount();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getContributionamount();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional common.UUID UserUuid = 1;
 * @return {?proto.common.UUID}
 */
proto.proto.Loyalty.prototype.getUseruuid = function() {
  return /** @type{?proto.common.UUID} */ (
    jspb.Message.getWrapperField(this, internal_pkg_delivery_grpc_commonProto_common_pb.UUID, 1));
};


/**
 * @param {?proto.common.UUID|undefined} value
 * @return {!proto.proto.Loyalty} returns this
*/
proto.proto.Loyalty.prototype.setUseruuid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.Loyalty} returns this
 */
proto.proto.Loyalty.prototype.clearUseruuid = function() {
  return this.setUseruuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.Loyalty.prototype.hasUseruuid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string Status = 2;
 * @return {string}
 */
proto.proto.Loyalty.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Loyalty} returns this
 */
proto.proto.Loyalty.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 Discount = 3;
 * @return {number}
 */
proto.proto.Loyalty.prototype.getDiscount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.Loyalty} returns this
 */
proto.proto.Loyalty.prototype.setDiscount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional float ContributionAmount = 4;
 * @return {number}
 */
proto.proto.Loyalty.prototype.getContributionamount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.proto.Loyalty} returns this
 */
proto.proto.Loyalty.prototype.setContributionamount = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


goog.object.extend(exports, proto.proto);
