// source: internal/pkg/delivery/grpc/reservation-service/proto/scheme.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var internal_pkg_delivery_grpc_commonProto_common_pb = require('../../../../../../internal/pkg/delivery/grpc/commonProto/common_pb.js');
goog.object.extend(proto, internal_pkg_delivery_grpc_commonProto_common_pb);
goog.exportSymbol('proto.proto.Reservation', null, global);
goog.exportSymbol('proto.proto.Reservations', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.Reservation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.Reservation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.Reservation.displayName = 'proto.proto.Reservation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.Reservations = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.Reservations.repeatedFields_, null);
};
goog.inherits(proto.proto.Reservations, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.Reservations.displayName = 'proto.proto.Reservations';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.Reservation.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.Reservation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.Reservation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Reservation.toObject = function(includeInstance, msg) {
  var f, obj = {
    reservationuuid: (f = msg.getReservationuuid()) && internal_pkg_delivery_grpc_commonProto_common_pb.UUID.toObject(includeInstance, f),
    roomuuid: (f = msg.getRoomuuid()) && internal_pkg_delivery_grpc_commonProto_common_pb.UUID.toObject(includeInstance, f),
    useruuid: (f = msg.getUseruuid()) && internal_pkg_delivery_grpc_commonProto_common_pb.UUID.toObject(includeInstance, f),
    paymentuuid: (f = msg.getPaymentuuid()) && internal_pkg_delivery_grpc_commonProto_common_pb.UUID.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 5, ""),
    date: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.Reservation}
 */
proto.proto.Reservation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.Reservation;
  return proto.proto.Reservation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.Reservation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.Reservation}
 */
proto.proto.Reservation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new internal_pkg_delivery_grpc_commonProto_common_pb.UUID;
      reader.readMessage(value,internal_pkg_delivery_grpc_commonProto_common_pb.UUID.deserializeBinaryFromReader);
      msg.setReservationuuid(value);
      break;
    case 2:
      var value = new internal_pkg_delivery_grpc_commonProto_common_pb.UUID;
      reader.readMessage(value,internal_pkg_delivery_grpc_commonProto_common_pb.UUID.deserializeBinaryFromReader);
      msg.setRoomuuid(value);
      break;
    case 3:
      var value = new internal_pkg_delivery_grpc_commonProto_common_pb.UUID;
      reader.readMessage(value,internal_pkg_delivery_grpc_commonProto_common_pb.UUID.deserializeBinaryFromReader);
      msg.setUseruuid(value);
      break;
    case 4:
      var value = new internal_pkg_delivery_grpc_commonProto_common_pb.UUID;
      reader.readMessage(value,internal_pkg_delivery_grpc_commonProto_common_pb.UUID.deserializeBinaryFromReader);
      msg.setPaymentuuid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.Reservation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.Reservation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.Reservation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Reservation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReservationuuid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      internal_pkg_delivery_grpc_commonProto_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getRoomuuid();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      internal_pkg_delivery_grpc_commonProto_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getUseruuid();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      internal_pkg_delivery_grpc_commonProto_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getPaymentuuid();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      internal_pkg_delivery_grpc_commonProto_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDate();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
};


/**
 * optional common.UUID ReservationUuid = 1;
 * @return {?proto.common.UUID}
 */
proto.proto.Reservation.prototype.getReservationuuid = function() {
  return /** @type{?proto.common.UUID} */ (
    jspb.Message.getWrapperField(this, internal_pkg_delivery_grpc_commonProto_common_pb.UUID, 1));
};


/**
 * @param {?proto.common.UUID|undefined} value
 * @return {!proto.proto.Reservation} returns this
*/
proto.proto.Reservation.prototype.setReservationuuid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.Reservation} returns this
 */
proto.proto.Reservation.prototype.clearReservationuuid = function() {
  return this.setReservationuuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.Reservation.prototype.hasReservationuuid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional common.UUID RoomUuid = 2;
 * @return {?proto.common.UUID}
 */
proto.proto.Reservation.prototype.getRoomuuid = function() {
  return /** @type{?proto.common.UUID} */ (
    jspb.Message.getWrapperField(this, internal_pkg_delivery_grpc_commonProto_common_pb.UUID, 2));
};


/**
 * @param {?proto.common.UUID|undefined} value
 * @return {!proto.proto.Reservation} returns this
*/
proto.proto.Reservation.prototype.setRoomuuid = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.Reservation} returns this
 */
proto.proto.Reservation.prototype.clearRoomuuid = function() {
  return this.setRoomuuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.Reservation.prototype.hasRoomuuid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional common.UUID UserUuid = 3;
 * @return {?proto.common.UUID}
 */
proto.proto.Reservation.prototype.getUseruuid = function() {
  return /** @type{?proto.common.UUID} */ (
    jspb.Message.getWrapperField(this, internal_pkg_delivery_grpc_commonProto_common_pb.UUID, 3));
};


/**
 * @param {?proto.common.UUID|undefined} value
 * @return {!proto.proto.Reservation} returns this
*/
proto.proto.Reservation.prototype.setUseruuid = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.Reservation} returns this
 */
proto.proto.Reservation.prototype.clearUseruuid = function() {
  return this.setUseruuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.Reservation.prototype.hasUseruuid = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional common.UUID PaymentUuid = 4;
 * @return {?proto.common.UUID}
 */
proto.proto.Reservation.prototype.getPaymentuuid = function() {
  return /** @type{?proto.common.UUID} */ (
    jspb.Message.getWrapperField(this, internal_pkg_delivery_grpc_commonProto_common_pb.UUID, 4));
};


/**
 * @param {?proto.common.UUID|undefined} value
 * @return {!proto.proto.Reservation} returns this
*/
proto.proto.Reservation.prototype.setPaymentuuid = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.Reservation} returns this
 */
proto.proto.Reservation.prototype.clearPaymentuuid = function() {
  return this.setPaymentuuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.Reservation.prototype.hasPaymentuuid = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string Status = 5;
 * @return {string}
 */
proto.proto.Reservation.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.Reservation} returns this
 */
proto.proto.Reservation.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 date = 6;
 * @return {number}
 */
proto.proto.Reservation.prototype.getDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.Reservation} returns this
 */
proto.proto.Reservation.prototype.setDate = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.Reservations.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.Reservations.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.Reservations.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.Reservations} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Reservations.toObject = function(includeInstance, msg) {
  var f, obj = {
    valueList: jspb.Message.toObjectList(msg.getValueList(),
    proto.proto.Reservation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.Reservations}
 */
proto.proto.Reservations.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.Reservations;
  return proto.proto.Reservations.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.Reservations} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.Reservations}
 */
proto.proto.Reservations.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.proto.Reservation;
      reader.readMessage(value,proto.proto.Reservation.deserializeBinaryFromReader);
      msg.addValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.Reservations.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.Reservations.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.Reservations} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Reservations.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValueList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.proto.Reservation.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Reservation Value = 1;
 * @return {!Array<!proto.proto.Reservation>}
 */
proto.proto.Reservations.prototype.getValueList = function() {
  return /** @type{!Array<!proto.proto.Reservation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.Reservation, 1));
};


/**
 * @param {!Array<!proto.proto.Reservation>} value
 * @return {!proto.proto.Reservations} returns this
*/
proto.proto.Reservations.prototype.setValueList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.proto.Reservation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.Reservation}
 */
proto.proto.Reservations.prototype.addValue = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.proto.Reservation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.Reservations} returns this
 */
proto.proto.Reservations.prototype.clearValueList = function() {
  return this.setValueList([]);
};


goog.object.extend(exports, proto.proto);
