#!/bin/sh

export JWT_KEY="DEVELOP_KEY"
export ADMIN_ID="DEVELOP_ID"
export ADMIN_SECRET="DEVELOP_SECRET"

export USER_LOYALTY_SERVICE_URL="localhost:3004"
export USER_LOYALTY_SERVICE_ADMIN_ID="DEVELOP_ID"
export USER_LOYALTY_SERVICE_ADMIN_SECRET="DEVELOP_SECRET"
export HOTEL_SERVICE_URL="localhost:3003"
export HOTEL_SERVICE_ADMIN_ID="DEVELOP_ID"
export HOTEL_SERVICE_ADMIN_SECRET="DEVELOP_SECRET"
export PAYMENT_SERVICE_URL="localhost:3005"
export PAYMENT_SERVICE_ADMIN_ID="DEVELOP_ID"
export PAYMENT_SERVICE_ADMIN_SECRET="DEVELOP_SECRET"
export USER_SERVICE_URL="localhost:3002"
export USER_SERVICE_ADMIN_ID="DEVELOP_ID"
export USER_SERVICE_ADMIN_SECRET="DEVELOP_SECRET"
export RESERVATION_SERVICE_URL="localhost:3001"
export RESERVATION_SERVICE_ADMIN_ID="DEVELOP_ID"
export RESERVATION_SERVICE_ADMIN_SECRET="DEVELOP_SECRET"

export GATEWAY_ADDRESS="192.168.31.112"
export GATEWAY_SERVICE_PORT="3000"
