name: Build project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Deploy-loyalty-service:
    name: loyalty-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy loyalty
        uses: appleboy/ssh-action@master
        with:
          host: loyalty.bookinghotelservice.ru
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull -f
            export JWT_KEY=${{ secrets.LOYALTY_JWT_KEY }} \
              ADMIN_ID=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_ID }} \
              ADMIN_SECRET=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_SECRET }} \
              LOYALTY_SERVICE_PORT=${{ secrets.LOYALTY_SERVICE_PORT }}
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose --env-file ./envfile --service-ports -d loyalty-service

  Deploy-auth-service:
    name: auth-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy auth
        uses: appleboy/ssh-action@master
        with:
          host: auth.bookinghotelservice.ru
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: JWT_KEY, ADMIN_ID, ADMIN_SECRET, USER_LOYALTY_SERVICE_URL, USER_LOYALTY_SERVICE_ADMIN_ID, USER_LOYALTY_SERVICE_ADMIN_SECRET, AUTH_SERVICE_PORT
          script_stop: true
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull -f
            export JWT_KEY=${{ secrets.AUTH_JWT_KEY }} \
              ADMIN_ID=${{ secrets.USER_SERVICE_ADMIN_ID }} \
              ADMIN_SECRET=${{ secrets.USER_SERVICE_ADMIN_SECRET }} \
              USER_LOYALTY_SERVICE_URL=${{ secrets.USER_LOYALTY_SERVICE_URL }} \
              USER_LOYALTY_SERVICE_ADMIN_ID=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_ID }} \
              USER_LOYALTY_SERVICE_ADMIN_SECRET=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_SECRET }}
              AUTH_SERVICE_PORT=${{ secrets.AUTH_SERVICE_PORT }}
            env > envfile
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose --env-file ./envfile run --service-ports -d auth-service
            
  Deploy-hotel-service:
    name: hotel-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy hotel
        uses: appleboy/ssh-action@master
        with:
          host: hotel.bookinghotelservice.ru
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull -f
            export JWT_KEY=${{ secrets.HOTEL_JWT_KEY }} \
              ADMIN_ID=${{ secrets.HOTEL_SERVICE_ADMIN_ID }} \
              ADMIN_SECRET=${{ secrets.HOTEL_SERVICE_ADMIN_SECRET }} \
              HOTEL_SERVICE_PORT=${{ secrets.HOTEL_SERVICE_PORT }}
            env > envfile
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose --env-file ./envfile run --service-ports -d hotel-service
            
  Deploy-payment-service:
    name: payment-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy payment
        uses: appleboy/ssh-action@master
        with:
          host: payment.bookinghotelservice.ru
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull -f
            export JWT_KEY=${{ secrets.PAYMENT_JWT_KEY }} \
              ADMIN_ID=${{ secrets.PAYMENT_SERVICE_ADMIN_ID }} \
              ADMIN_SECRET=${{ secrets.PAYMENT_SERVICE_ADMIN_SECRET }} \
              USER_LOYALTY_SERVICE_URL=${{ secrets.USER_LOYALTY_SERVICE_URL }} \
              USER_LOYALTY_SERVICE_ADMIN_ID=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_ID }} \
              USER_LOYALTY_SERVICE_ADMIN_SECRET=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_SECRET }} \
              USER_SERVICE_URL=${{ secrets.USER_SERVICE_URL }} \
              USER_SERVICE_ADMIN_ID=${{ secrets.USER_SERVICE_ADMIN_ID }} \
              USER_SERVICE_ADMIN_SECRET=${{ secrets.USER_SERVICE_ADMIN_SECRET }} \
              PAYMENT_SERVICE_PORT=${{ secrets.PAYMENT_SERVICE_PORT }}
            env > envfile
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose --env-file ./envfile run --service-ports -d payment-service
            
  Deploy-reservation-service:
    name: reservation-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy reservation
        uses: appleboy/ssh-action@master
        with:
          host: reservation.bookinghotelservice.ru
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull -f
            export JWT_KEY=${{ secrets.RESERVATION_JWT_KEY }} \
              ADMIN_ID=${{ secrets.RESERVATION_SERVICE_ADMIN_ID }} \
              ADMIN_SECRET=${{ secrets.RESERVATION_SERVICE_ADMIN_SECRET }} \
              USER_LOYALTY_SERVICE_URL=${{ secrets.USER_LOYALTY_SERVICE_URL }} \
              USER_LOYALTY_SERVICE_ADMIN_ID=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_ID }} \
              USER_LOYALTY_SERVICE_ADMIN_SECRET=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_SECRET }} \
              USER_SERVICE_URL=${{ secrets.USER_SERVICE_URL }} \
              USER_SERVICE_ADMIN_ID=${{ secrets.USER_SERVICE_ADMIN_ID }} \
              USER_SERVICE_ADMIN_SECRET=${{ secrets.USER_SERVICE_ADMIN_SECRET }} \
              PAYMENT_SERVICE_URL=${{ secrets.PAYMENT_SERVICE_URL }} \
              PAYMENT_SERVICE_ADMIN_ID=${{ secrets.PAYMENT_SERVICE_ADMIN_ID }} \
              PAYMENT_SERVICE_ADMIN_SECRET=${{ secrets.PAYMENT_SERVICE_ADMIN_SECRET }} \
              HOTEL_SERVICE_URL=${{ secrets.HOTEL_SERVICE_URL }} \
              HOTEL_SERVICE_ADMIN_ID=${{ secrets.HOTEL_SERVICE_ADMIN_ID }} \
              HOTEL_SERVICE_ADMIN_SECRET=${{ secrets.HOTEL_SERVICE_ADMIN_SECRET }} \
              RESERVATION_SERVICE_PORT=${{ secrets.RESERVATION_SERVICE_PORT }}
            env > envfile
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose --env-file ./envfile run --service-ports -d reservation-service
            
  Deploy-gateway-service:
    name: gateway-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy gateway
        uses: appleboy/ssh-action@master
        with:
          host: gateway.bookinghotelservice.ru
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull -f
            export JWT_KEY=${{ secrets.GATEWAY_JWT_KEY }} \
              ADMIN_ID=${{ secrets.GATEWAY_SERVICE_ADMIN_ID }} \
              ADMIN_SECRET=${{ secrets.GATEWAY_SERVICE_ADMIN_SECRET }} \
              USER_LOYALTY_SERVICE_URL=${{ secrets.USER_LOYALTY_SERVICE_URL }} \
              USER_LOYALTY_SERVICE_ADMIN_ID=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_ID }} \
              USER_LOYALTY_SERVICE_ADMIN_SECRET=${{ secrets.USER_LOYALTY_SERVICE_ADMIN_SECRET }} \
              USER_SERVICE_URL=${{ secrets.USER_SERVICE_URL }} \
              USER_SERVICE_ADMIN_ID=${{ secrets.USER_SERVICE_ADMIN_ID }} \
              USER_SERVICE_ADMIN_SECRET=${{ secrets.USER_SERVICE_ADMIN_SECRET }} \
              PAYMENT_SERVICE_URL=${{ secrets.PAYMENT_SERVICE_URL }} \
              PAYMENT_SERVICE_ADMIN_ID=${{ secrets.PAYMENT_SERVICE_ADMIN_ID }} \
              PAYMENT_SERVICE_ADMIN_SECRET=${{ secrets.PAYMENT_SERVICE_ADMIN_SECRET }} \
              HOTEL_SERVICE_URL=${{ secrets.HOTEL_SERVICE_URL }} \
              HOTEL_SERVICE_ADMIN_ID=${{ secrets.HOTEL_SERVICE_ADMIN_ID }} \
              HOTEL_SERVICE_ADMIN_SECRET=${{ secrets.HOTEL_SERVICE_ADMIN_SECRET }} \
              RESERVATION_SERVICE_URL=${{ secrets.RESERVATION_SERVICE_URL }} \
              RESERVATION_SERVICE_ADMIN_ID=${{ secrets.RESERVATION_SERVICE_ADMIN_ID }} \
              RESERVATION_SERVICE_ADMIN_SECRET=${{ secrets.RESERVATION_SERVICE_ADMIN_SECRET }} \
              GATEWAY_ADDRESS=${{ secrets.GATEWAY_ADDRESS }} \
              GATEWAY_SERVICE_PORT=${{ secrets.GATEWAY_SERVICE_PORT }}
            env > envfile
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose --env-file ./envfile run --service-ports -d gateway-service
            ./scripts/gen-envoy-conf.sh
            sudo docker-compose run --service-ports -d envoy
            
  Deploy-frontend:
    name: frontend-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: bookinghotelservice.ru
          username: ${{ secrets.FRONTUSER }}
          password: ${{ secrets.FRONTUSER }}
          script_stop: true
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull -f
            cd frontend
            npm i
            npm run build
            sudo docker-compose down
            sudo docker-compose up
